import numpy as np
import matplotlib.pyplot as plt
import glob
import os
import pickle
import json
import pandas as pd
import random
import tensorflow as tf
from tensorflow import keras
from time import time
from tensorflow.python.keras.callbacks import TensorBoard
from IPython.display import clear_output
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, concatenate, Dense, Flatten, Add, LeakyReLU, Dropout
print("GPU IS AVAILABLE" if tf.test.is_gpu_available() else "NO GPU")

strategy = tf.distribute.MirroredStrategy()

input_shape = (720,1280,1)

with strategy.scope():
# Ref
# t - 1
    t_min_1_ref_in = Input(shape=input_shape, name="t_min_1_ref_in")
    t_min_1_ref = Conv2D(32,3, kernel_regularizer='l2')(t_min_1_ref_in)
    t_min_1_ref = Dropout(0.2)(t_min_1_ref)
    t_min_1_ref = LeakyReLU(alpha=0.1)(t_min_1_ref)
    t_min_1_ref = MaxPooling2D(pool_size=(2,2))(t_min_1_ref)
    t_min_1_ref = Conv2D(32,3, kernel_regularizer='l2')(t_min_1_ref)
    t_min_1_ref = Dropout(0.2)(t_min_1_ref)
    t_min_1_ref = LeakyReLU(alpha=0.1)(t_min_1_ref)
    t_min_1_ref = MaxPooling2D(pool_size=(2,2))(t_min_1_ref)
    t_min_1_ref = Conv2D(64,3, kernel_regularizer='l2')(t_min_1_ref)
    t_min_1_ref = Dropout(0.2)(t_min_1_ref)
    t_min_1_ref = LeakyReLU(alpha=0.1)(t_min_1_ref)
    t_min_1_ref = MaxPooling2D(pool_size=(2,2))(t_min_1_ref)
    t_min_1_ref = Conv2D(64,3, kernel_regularizer='l2')(t_min_1_ref)
    t_min_1_ref = Dropout(0.2)(t_min_1_ref)
    t_min_1_ref = LeakyReLU(alpha=0.1)(t_min_1_ref)
    t_min_1_ref = MaxPooling2D(pool_size=(2,2))(t_min_1_ref)
    t_min_1_ref = Conv2D(128,3, kernel_regularizer='l2')(t_min_1_ref)
    t_min_1_ref = Dropout(0.2)(t_min_1_ref)
    t_min_1_ref = LeakyReLU(alpha=0.1)(t_min_1_ref)
    t_min_1_ref = MaxPooling2D(pool_size=(2,2))(t_min_1_ref)
    t_min_1_ref = Conv2D(128,3, kernel_regularizer='l2')(t_min_1_ref)
    t_min_1_ref = Dropout(0.2)(t_min_1_ref)
    t_min_1_ref = LeakyReLU(alpha=0.1)(t_min_1_ref)
    t_min_1_ref = MaxPooling2D(pool_size=(2,2))(t_min_1_ref)
    t_min_1_ref = Conv2D(256,(2,5), kernel_regularizer='l2')(t_min_1_ref)
    t_min_1_ref = Dropout(0.2)(t_min_1_ref)
    t_min_1_ref = LeakyReLU(alpha=0.1)(t_min_1_ref)
    t_min_1_ref = MaxPooling2D(pool_size=(2,2))(t_min_1_ref)
    t_min_1_ref = Conv2D(256,(2,5), kernel_regularizer='l2')(t_min_1_ref)
    t_min_1_ref = Dropout(0.2)(t_min_1_ref)
    t_min_1_ref = LeakyReLU(alpha=0.1)(t_min_1_ref)

    # t
    t_ref_in_Y = Input(shape=input_shape, name="t_ref_in_Y")
    t_ref_Y = Conv2D(32,3, kernel_regularizer='l2')(t_ref_in_Y)
    t_ref_Y = LeakyReLU(alpha=0.1)(t_ref_Y)
    t_ref_Y = Dropout(0.2)(t_ref_Y)
    t_ref_Y = MaxPooling2D(pool_size=(2,2))(t_ref_Y)
    t_ref_Y = Conv2D(32,3, kernel_regularizer='l2')(t_ref_Y)
    t_ref_Y = Dropout(0.2)(t_ref_Y)
    t_ref_Y = LeakyReLU(alpha=0.1)(t_ref_Y)
    t_ref_Y = MaxPooling2D(pool_size=(2,2))(t_ref_Y)
    t_ref_Y = Conv2D(64,3, kernel_regularizer='l2')(t_ref_Y)
    t_ref_Y = Dropout(0.2)(t_ref_Y)
    t_ref_Y = LeakyReLU(alpha=0.1)(t_ref_Y)
    t_ref_Y = MaxPooling2D(pool_size=(2,2))(t_ref_Y)
    t_ref_Y = Conv2D(64,3, kernel_regularizer='l2')(t_ref_Y)
    t_ref_Y = Dropout(0.2)(t_ref_Y)
    t_ref_Y = LeakyReLU(alpha=0.1)(t_ref_Y)
    t_ref_Y = MaxPooling2D(pool_size=(2,2))(t_ref_Y)
    t_ref_Y = Conv2D(128,3, kernel_regularizer='l2')(t_ref_Y)
    t_ref_Y = Dropout(0.2)(t_ref_Y)
    t_ref_Y = LeakyReLU(alpha=0.1)(t_ref_Y)
    t_ref_Y = MaxPooling2D(pool_size=(2,2))(t_ref_Y)
    t_ref_Y = Conv2D(128,3, kernel_regularizer='l2')(t_ref_Y)
    t_ref_Y = Dropout(0.2)(t_ref_Y)
    t_ref_Y = LeakyReLU(alpha=0.1)(t_ref_Y)
    t_ref_Y = MaxPooling2D(pool_size=(2,2))(t_ref_Y)
    t_ref_Y = Conv2D(256,(2,5), kernel_regularizer='l2')(t_ref_Y)
    t_ref_Y = Dropout(0.2)(t_ref_Y)
    t_ref_Y = LeakyReLU(alpha=0.1)(t_ref_Y)
    t_ref_Y = MaxPooling2D(pool_size=(2,2))(t_ref_Y)
    t_ref_Y = Conv2D(256,(2,5), kernel_regularizer='l2')(t_ref_Y)
    t_ref_Y = Dropout(0.2)(t_ref_Y)
    t_ref_Y = LeakyReLU(alpha=0.1)(t_ref_Y)


    # t + 1
    t_plus_1_ref_in = Input(shape=input_shape, name="t_plus_1_ref_in")
    t_plus_1_ref = Conv2D(32,3, kernel_regularizer='l2')(t_plus_1_ref_in)
    t_plus_1_ref = Dropout(0.2)(t_plus_1_ref)
    t_plus_1_ref = LeakyReLU(alpha=0.1)(t_plus_1_ref)
    t_plus_1_ref = MaxPooling2D(pool_size=(2,2))(t_plus_1_ref)
    t_plus_1_ref = Conv2D(32,3, kernel_regularizer='l2')(t_plus_1_ref)
    t_plus_1_ref = Dropout(0.2)(t_plus_1_ref)
    t_plus_1_ref = LeakyReLU(alpha=0.1)(t_plus_1_ref)
    t_plus_1_ref = MaxPooling2D(pool_size=(2,2))(t_plus_1_ref)
    t_plus_1_ref = Conv2D(64,3, kernel_regularizer='l2')(t_plus_1_ref)
    t_plus_1_ref = Dropout(0.2)(t_plus_1_ref)
    t_plus_1_ref = LeakyReLU(alpha=0.1)(t_plus_1_ref)
    t_plus_1_ref = MaxPooling2D(pool_size=(2,2))(t_plus_1_ref)
    t_plus_1_ref = Conv2D(64,3, kernel_regularizer='l2')(t_plus_1_ref)
    t_plus_1_ref = Dropout(0.2)(t_plus_1_ref)
    t_plus_1_ref = LeakyReLU(alpha=0.1)(t_plus_1_ref)
    t_plus_1_ref = MaxPooling2D(pool_size=(2,2))(t_plus_1_ref)
    t_plus_1_ref = Conv2D(128,3, kernel_regularizer='l2')(t_plus_1_ref)
    t_plus_1_ref = Dropout(0.2)(t_plus_1_ref)
    t_plus_1_ref = LeakyReLU(alpha=0.1)(t_plus_1_ref)
    t_plus_1_ref = MaxPooling2D(pool_size=(2,2))(t_plus_1_ref)
    t_plus_1_ref = Conv2D(128,3, kernel_regularizer='l2')(t_plus_1_ref)
    t_plus_1_ref = Dropout(0.2)(t_plus_1_ref)
    t_plus_1_ref = LeakyReLU(alpha=0.1)(t_plus_1_ref)
    t_plus_1_ref = MaxPooling2D(pool_size=(2,2))(t_plus_1_ref)
    t_plus_1_ref = Conv2D(256,(2,5), kernel_regularizer='l2')(t_plus_1_ref)
    t_plus_1_ref = Dropout(0.2)(t_plus_1_ref)
    t_plus_1_ref = LeakyReLU(alpha=0.1)(t_plus_1_ref)
    t_plus_1_ref = MaxPooling2D(pool_size=(2,2))(t_plus_1_ref)
    t_plus_1_ref = Conv2D(256,(2,5), kernel_regularizer='l2')(t_plus_1_ref)
    t_plus_1_ref = Dropout(0.2)(t_plus_1_ref)
    t_plus_1_ref = LeakyReLU(alpha=0.1)(t_plus_1_ref)

    ref_cat = concatenate([t_min_1_ref,t_ref_Y,t_plus_1_ref])
    ref_cat_Conv = Conv2D(768,3, kernel_regularizer='l2')(ref_cat)
    ref_cat_Conv = Dropout(0.2)(ref_cat_Conv)
    ref_cat_Conv = LeakyReLU(alpha=0.1)(ref_cat_Conv)


    # Dist
    # t - 1
    t_min_1_dist_in = Input(shape=input_shape, name="t_min_1_dist_in")
    t_min_1_dist = Conv2D(32,3, kernel_regularizer='l2')(t_min_1_dist_in)
    t_min_1_dist = Dropout(0.2)(t_min_1_dist)
    t_min_1_dist = LeakyReLU(alpha=0.1)(t_min_1_dist)
    t_min_1_dist = MaxPooling2D(pool_size=(2,2))(t_min_1_dist)
    t_min_1_dist = Conv2D(32,3, kernel_regularizer='l2')(t_min_1_dist)
    t_min_1_dist = Dropout(0.2)(t_min_1_dist)
    t_min_1_dist = LeakyReLU(alpha=0.1)(t_min_1_dist)
    t_min_1_dist = MaxPooling2D(pool_size=(2,2))(t_min_1_dist)
    t_min_1_dist = Conv2D(64,3, kernel_regularizer='l2')(t_min_1_dist)
    t_min_1_dist = Dropout(0.2)(t_min_1_dist)
    t_min_1_dist = LeakyReLU(alpha=0.1)(t_min_1_dist)
    t_min_1_dist = MaxPooling2D(pool_size=(2,2))(t_min_1_dist)
    t_min_1_dist = Conv2D(64,3, kernel_regularizer='l2')(t_min_1_dist)
    t_min_1_dist = Dropout(0.2)(t_min_1_dist)
    t_min_1_dist = LeakyReLU(alpha=0.1)(t_min_1_dist)
    t_min_1_dist = MaxPooling2D(pool_size=(2,2))(t_min_1_dist)
    t_min_1_dist = Conv2D(128,3, kernel_regularizer='l2')(t_min_1_dist)
    t_min_1_dist = Dropout(0.2)(t_min_1_dist)
    t_min_1_dist = LeakyReLU(alpha=0.1)(t_min_1_dist)
    t_min_1_dist = MaxPooling2D(pool_size=(2,2))(t_min_1_dist)
    t_min_1_dist = Conv2D(128,3, kernel_regularizer='l2')(t_min_1_dist)
    t_min_1_dist = Dropout(0.2)(t_min_1_dist)
    t_min_1_dist = LeakyReLU(alpha=0.1)(t_min_1_dist)
    t_min_1_dist = MaxPooling2D(pool_size=(2,2))(t_min_1_dist)
    t_min_1_dist = Conv2D(256,(2,5), kernel_regularizer='l2')(t_min_1_dist)
    t_min_1_dist = Dropout(0.2)(t_min_1_dist)
    t_min_1_dist = LeakyReLU(alpha=0.1)(t_min_1_dist)
    t_min_1_dist = MaxPooling2D(pool_size=(2,2))(t_min_1_dist)
    t_min_1_dist = Conv2D(256,(2,5), kernel_regularizer='l2')(t_min_1_dist)
    t_min_1_dist = Dropout(0.2)(t_min_1_dist)
    t_min_1_dist = LeakyReLU(alpha=0.1)(t_min_1_dist)

    # t
    t_dist_in_Y = Input(shape=input_shape, name="t_dist_in_Y")
    t_dist_Y = Conv2D(32,3, kernel_regularizer='l2')(t_dist_in_Y)
    t_dist_Y = Dropout(0.2)(t_dist_Y)
    t_dist_Y = LeakyReLU(alpha=0.1)(t_dist_Y)
    t_dist_Y = MaxPooling2D(pool_size=(2,2))(t_dist_Y)
    t_dist_Y = Conv2D(32,3, kernel_regularizer='l2')(t_dist_Y)
    t_dist_Y = Dropout(0.2)(t_dist_Y)
    t_dist_Y = LeakyReLU(alpha=0.1)(t_dist_Y)
    t_dist_Y = MaxPooling2D(pool_size=(2,2))(t_dist_Y)
    t_dist_Y = Conv2D(64,3, kernel_regularizer='l2')(t_dist_Y)
    t_dist_Y = Dropout(0.2)(t_dist_Y)
    t_dist_Y = LeakyReLU(alpha=0.1)(t_dist_Y)
    t_dist_Y = MaxPooling2D(pool_size=(2,2))(t_dist_Y)
    t_dist_Y = Conv2D(64,3, kernel_regularizer='l2')(t_dist_Y)
    t_dist_Y = Dropout(0.2)(t_dist_Y)
    t_dist_Y = LeakyReLU(alpha=0.1)(t_dist_Y)
    t_dist_Y = MaxPooling2D(pool_size=(2,2))(t_dist_Y)
    t_dist_Y = Conv2D(128,3, kernel_regularizer='l2')(t_dist_Y)
    t_dist_Y = Dropout(0.2)(t_dist_Y)
    t_dist_Y = LeakyReLU(alpha=0.1)(t_dist_Y)
    t_dist_Y = MaxPooling2D(pool_size=(2,2))(t_dist_Y)
    t_dist_Y = Conv2D(128,3, kernel_regularizer='l2')(t_dist_Y)
    t_dist_Y = Dropout(0.2)(t_dist_Y)
    t_dist_Y = LeakyReLU(alpha=0.1)(t_dist_Y)
    t_dist_Y = MaxPooling2D(pool_size=(2,2))(t_dist_Y)
    t_dist_Y = Conv2D(256,(2,5), kernel_regularizer='l2')(t_dist_Y)
    t_dist_Y = Dropout(0.2)(t_dist_Y)
    t_dist_Y = LeakyReLU(alpha=0.1)(t_dist_Y)
    t_dist_Y = MaxPooling2D(pool_size=(2,2))(t_dist_Y)
    t_dist_Y = Conv2D(256,(2,5), kernel_regularizer='l2')(t_dist_Y)
    t_dist_Y = Dropout(0.2)(t_dist_Y)
    t_dist_Y = LeakyReLU(alpha=0.1)(t_dist_Y)

    # t + 1
    t_plus_1_dist_in = Input(shape=input_shape, name="t_plus_1_dist_in")
    t_plus_1_dist = Conv2D(32,3, kernel_regularizer='l2')(t_plus_1_dist_in)
    t_plus_1_dist = Dropout(0.2)(t_plus_1_dist)
    t_plus_1_dist = LeakyReLU(alpha=0.1)(t_plus_1_dist)
    t_plus_1_dist = MaxPooling2D(pool_size=(2,2))(t_plus_1_dist)
    t_plus_1_dist = Conv2D(32,3, kernel_regularizer='l2')(t_plus_1_dist)
    t_plus_1_dist = Dropout(0.2)(t_plus_1_dist)
    t_plus_1_dist = LeakyReLU(alpha=0.1)(t_plus_1_dist)
    t_plus_1_dist = MaxPooling2D(pool_size=(2,2))(t_plus_1_dist)
    t_plus_1_dist = Conv2D(64,3, kernel_regularizer='l2')(t_plus_1_dist)
    t_plus_1_dist = Dropout(0.2)(t_plus_1_dist)
    t_plus_1_dist = LeakyReLU(alpha=0.1)(t_plus_1_dist)
    t_plus_1_dist = MaxPooling2D(pool_size=(2,2))(t_plus_1_dist)
    t_plus_1_dist = Conv2D(64,3, kernel_regularizer='l2')(t_plus_1_dist)
    t_plus_1_dist = Dropout(0.2)(t_plus_1_dist)
    t_plus_1_dist = LeakyReLU(alpha=0.1)(t_plus_1_dist)
    t_plus_1_dist = MaxPooling2D(pool_size=(2,2))(t_plus_1_dist)
    t_plus_1_dist = Conv2D(128,3, kernel_regularizer='l2')(t_plus_1_dist)
    t_plus_1_dist = Dropout(0.2)(t_plus_1_dist)
    t_plus_1_dist = LeakyReLU(alpha=0.1)(t_plus_1_dist)
    t_plus_1_dist = MaxPooling2D(pool_size=(2,2))(t_plus_1_dist)
    t_plus_1_dist = Conv2D(128,3, kernel_regularizer='l2')(t_plus_1_dist)
    t_plus_1_dist = Dropout(0.2)(t_plus_1_dist)
    t_plus_1_dist = LeakyReLU(alpha=0.1)(t_plus_1_dist)
    t_plus_1_dist = MaxPooling2D(pool_size=(2,2))(t_plus_1_dist)
    t_plus_1_dist = Conv2D(256,(2,5), kernel_regularizer='l2')(t_plus_1_dist)
    t_plus_1_dist = Dropout(0.2)(t_plus_1_dist)
    t_plus_1_dist = LeakyReLU(alpha=0.1)(t_plus_1_dist)
    t_plus_1_dist = MaxPooling2D(pool_size=(2,2))(t_plus_1_dist)
    t_plus_1_dist = Conv2D(256,(2,5), kernel_regularizer='l2')(t_plus_1_dist)
    t_plus_1_dist = Dropout(0.2)(t_plus_1_dist)
    t_plus_1_dist = LeakyReLU(alpha=0.1)(t_plus_1_dist)

    dist_cat = concatenate([t_min_1_dist,t_dist_Y,t_plus_1_dist])
    dist_cat_Conv = Conv2D(768,3, kernel_regularizer='l2')(dist_cat)
    dist_cat_Conv = Dropout(0.2)(dist_cat_Conv)
    dist_cat_Conv = LeakyReLU(alpha=0.1)(dist_cat_Conv)

    ref_dist_cat = concatenate([ref_cat_Conv,dist_cat_Conv])
    ref_dist_cat = Conv2D(768,(1,1), kernel_regularizer='l2')(ref_dist_cat)
    ref_dist_cat = Dropout(0.2)(ref_dist_cat)
    ref_dist_cat = LeakyReLU(alpha=0.1)(ref_dist_cat)

    ref_dist_cat = Flatten()(ref_dist_cat)
    ref_dist_cat = Dense(256, kernel_regularizer='l2')(ref_dist_cat)
    ref_dist_cat = Dropout(0.2)(ref_dist_cat)
    ref_dist_cat = LeakyReLU(alpha=0.1)(ref_dist_cat)
    ref_dist_cat = Dense(128, kernel_regularizer='l2')(ref_dist_cat)
    ref_dist_cat = Dropout(0.2)(ref_dist_cat)
    ref_dist_cat = LeakyReLU(alpha=0.1)(ref_dist_cat)
    ref_dist_cat = Dense(1, kernel_regularizer='l2')(ref_dist_cat)
    ref_dist_cat = LeakyReLU(alpha=0.1)(ref_dist_cat)


    ref_list_inputs = [t_min_1_ref_in,t_ref_in_Y,t_plus_1_ref_in]
    dist_list_inputs = [t_min_1_dist_in,t_dist_in_Y,t_plus_1_dist_in]
    loss_fn = keras.losses.MeanSquaredError()
    model = keras.models.Model(inputs = ref_list_inputs+dist_list_inputs, outputs= ref_dist_cat)
    optimizer = keras.optimizers.Adam(learning_rate=0.0001)
    model.compile(optimizer=optimizer, loss=loss_fn, metrics=['mse'])
    model.summary()
